#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Initialize the counter
count=1

# Loop until the counter reaches 10
until [ "$count" -gt 10 ]; do
  echo "Best School"
  count=$((count + 1))
done
