#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and Hi on the 9th time

# Initialize the counter
count=1

# Loop while the counter is less than or equal to 10
while [ "$count" -le 10 ]; do
  if [ "$count" -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  count=$((count + 1))
done
