#!/usr/bin/env bash
# a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.

# Display processes that contain the word 'bash' without using grep
ps -ef | awk '/bash/ {print}'
