#!/usr/bin/env bash
# Bash script to kill infinity and beyond script

# Find the PID of the running script
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the PID was found
if [ -n "$pid" ]; then
    kill "$pid"
    echo "Stopped process with PID: $pid"
else
    echo "No running process found for infinity_beyond.sh"
fi
